### ISSUE TITLE
ContactService.AddToCampaign {"Server returned a fault exception: [6] [Loading]Error loading follow-up sequence"}

### ISSUE THREAD

**Issue by leuwintintellibox** [EventDay/Infusionsoft.net#46]
```
 var customer = new Customer(application, apiKey);
var client = customer.Connect();
client.MethodListener = new ConsoleMethodListener();

int userId=1111;
int campaignId=35;

client.ContactService.AddToCampaign(userId, campaignId);
```
![2016-10-19_044455](https://cloud.githubusercontent.com/assets/13696570/19499967/f956e6d0-95b6-11e6-8d31-ceb50d64352b.png)

```

{"Server returned a fault exception: [6] [Loading]Error loading follow-up sequence"}


   at InfusionSoft.ServiceBase`1.TryInvoke[T](Func`1 func) in c:\Users\Admin\Downloads\Infusionsoft.net-master\Infusionsoft.net-master\src\InfusionSoft\ServiceBase.cs:line 61
   at InfusionSoft.ServiceBase`1.Invoke[T](Func`2 method) in c:\Users\Admin\Downloads\Infusionsoft.net-master\Infusionsoft.net-master\src\InfusionSoft\ServiceBase.cs:line 37
   at InfusionSoft.ContactServiceWrapper.AddToCampaign(Int32 contactId, Int32 campaignId) in c:\Users\Admin\Downloads\Infusionsoft.net-master\Infusionsoft.net-master\src\InfusionSoft\Wrappers\ContactServiceWrapper.cs:line 45
   at Sample.Program.Main() in c:\Users\Admin\Downloads\Infusionsoft.net-master\Infusionsoft.net-master\src\Sample\Program.cs:line 64
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by daveford** [comment]
Was this ever resolved? I am getting the same error.
